/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;
//import static Vistas.FormMenu.actualizarInterfaz;
//import static Vistas.FormMenu.contenedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProductoDTO;
import modeloDAO.productoDAO;
/**
 *
 * @author esther
 */
public class IFormStockVenta extends javax.swing.JInternalFrame {
    productoDAO pd;
    ArrayList<ProductoDTO> listaProductos = new ArrayList<>();
    
    DefaultTableModel modelo = new DefaultTableModel();
    public IFormStockVenta() {
        initComponents();
        establecerColumnas();
        mostrarTablaStock();
        
    }
    private void establecerColumnas(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        tblStock.setModel(modelo);
    }
    
    private IFormVenta formularioVenta;

    public void setFormularioVenta(IFormVenta formularioVenta) {
    this.formularioVenta = formularioVenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("STOCK");

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        int row = tblStock.getSelectedRow();
        IFormVenta v = new IFormVenta();
        try {
            // Verificar el stock
            int stock = Integer.parseInt(tblStock.getValueAt(row, 3).toString());
            if (stock == 0) {
                throw new IllegalArgumentException("Stock insuficiente. No se puede agregar el producto.");
            }
            // Si el stock es suficiente, continuar con el formulario "IFormVenta"
            if (formularioVenta != null && formularioVenta.x == 1) {
            formularioVenta.txtCodPro.setText(tblStock.getValueAt(row, 0).toString());
            formularioVenta.txtprecio.setText(tblStock.getValueAt(row, 2).toString());
            formularioVenta.txtStock.setText(tblStock.getValueAt(row, 3).toString());
            formularioVenta.txtcantidad.requestFocus();
            formularioVenta.x = 0;
            formularioVenta.pnlDatos.setVisible(true);
           
             dispose();}
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Stock", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblStockMouseClicked

    private void mostrarTablaStock(){
        eliminarElementosTabla();
         pd = new productoDAO();   
         listaProductos = pd.listarTodos();
        //Mostrar productos en la tabla stock
        for(int i=0;i<listaProductos.size();i++){
            Object[] data={ 
                listaProductos.get(i).getCod(),
                listaProductos.get(i).getDescripcion(),
                listaProductos.get(i).getPrecioUnit(),
                listaProductos.get(i).getStock(),
            };
            modelo.addRow(data);
        }  
    }
    
    public void eliminarElementosTabla(){
        for(int i=tblStock.getRowCount()-1;i>=0;i--){
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables
}
