/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;
import Clases.Producto;
import static Vistas.IFormProducto.listaProductos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lesly
 */
public class IFormInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFormInventario
     */
    //Declarar un objeto de la clase producto
    Producto p;
    //Instanciar el ArrayList como public static para que el IFormEntrada y el IFormSalida 
    //puedan tener acceso
    //public static ArrayList<Producto> listaProductos = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    public IFormInventario() {
        initComponents();
        establecerColumnas();
        mostrarTablaProductos();
    }
    private void establecerColumnas(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio Unit");
        modelo.addColumn("Stock");
        tblStock.setModel(modelo);
    }
    public void mostrarTablaProductos(){
        for(int i=tblStock.getRowCount()-1;i>=0;i--){
            modelo.removeRow(i);
        }
        //Mostrar productos en la tabla
        for(int i=0;i<listaProductos.size();i++){
            Object[] data={listaProductos.get(i).getCod(),listaProductos.get(i).getDescripcion(),
                //Revisar stock
                listaProductos.get(i).getCategoria(),listaProductos.get(i).getPrecioUnit(),};
            modelo.addRow(data);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlnventario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();

        setClosable(true);

        pnlnventario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Inventario de productos");

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStock);

        javax.swing.GroupLayout pnlnventarioLayout = new javax.swing.GroupLayout(pnlnventario);
        pnlnventario.setLayout(pnlnventarioLayout);
        pnlnventarioLayout.setHorizontalGroup(
            pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnventarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnlnventarioLayout.setVerticalGroup(
            pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnventarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlnventario;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables
}
