/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;
import static Vistas.FormMenu.actualizarInterfaz;
import static Vistas.FormMenu.contenedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProductoDTO;
import modeloDAO.productoDAO;

/**
 *
 * @author lesly
 */
public class IFormInventario extends javax.swing.JInternalFrame {
    //Declarar un objeto de la clase productoDAO
    productoDAO pd;
    ArrayList<ProductoDTO> listaProductos = new ArrayList<>();
    
    DefaultTableModel modelo = new DefaultTableModel();
    public IFormInventario() {
        initComponents();
        setSize(777,550);
        establecerColumnas();
        pnlbuscar.setVisible(false); 
    }
    private void establecerColumnas(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        tblInventario.setModel(modelo);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlnventario = new javax.swing.JPanel();
        txttitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        pnlbuscar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtidprod = new javax.swing.JRadioButton();
        rbtnombreprod = new javax.swing.JRadioButton();
        txtbuscarpor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setClosable(true);

        pnlnventario.setBackground(new java.awt.Color(255, 255, 255));

        txttitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        txttitulo.setText("Inventario de productos");

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        pnlbuscar.setBackground(new java.awt.Color(255, 255, 255));
        pnlbuscar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Buscar por:");

        buttonGroup1.add(rbtidprod);
        rbtidprod.setText("ID Producto");

        buttonGroup1.add(rbtnombreprod);
        rbtnombreprod.setText("Nombre del Producto");

        txtbuscarpor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuscarporMouseClicked(evt);
            }
        });
        txtbuscarpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarporActionPerformed(evt);
            }
        });
        txtbuscarpor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarporKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarporKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("STOCK");

        javax.swing.GroupLayout pnlbuscarLayout = new javax.swing.GroupLayout(pnlbuscar);
        pnlbuscar.setLayout(pnlbuscarLayout);
        pnlbuscarLayout.setHorizontalGroup(
            pnlbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbuscarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pnlbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtbuscarpor, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlbuscarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(rbtidprod)
                        .addGap(42, 42, 42)
                        .addComponent(rbtnombreprod)))
                .addContainerGap())
        );
        pnlbuscarLayout.setVerticalGroup(
            pnlbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnombreprod)
                    .addComponent(rbtidprod)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(txtbuscarpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlnventarioLayout = new javax.swing.GroupLayout(pnlnventario);
        pnlnventario.setLayout(pnlnventarioLayout);
        pnlnventarioLayout.setHorizontalGroup(
            pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnventarioLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlnventarioLayout.createSequentialGroup()
                        .addGroup(pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrar)
                            .addComponent(txttitulo))
                        .addGap(39, 39, 39)
                        .addComponent(pnlbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlnventarioLayout.setVerticalGroup(
            pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlnventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlnventarioLayout.createSequentialGroup()
                        .addComponent(pnlbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnlnventarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttitulo)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarporActionPerformed
        
    }//GEN-LAST:event_txtbuscarporActionPerformed

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
    
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarTablaStock();  
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtbuscarporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarporMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarporMouseClicked

    private void txtbuscarporKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporKeyPressed
          
    }//GEN-LAST:event_txtbuscarporKeyPressed

    private void txtbuscarporKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarporKeyReleased
     public void mostrarTablaStock(){
        eliminarElementosTabla();
         pd = new productoDAO();   
         listaProductos = pd.listarTodos();
        //Mostrar productos en la tabla stock
        for(int i=0;i<listaProductos.size();i++){
            Object[] data={ 
                listaProductos.get(i).getCod(),
                listaProductos.get(i).getDescripcion(),
                listaProductos.get(i).getPrecioUnit(),
                listaProductos.get(i).getStock(),
            };
            modelo.addRow(data);
        }  
    }
    
    public void eliminarElementosTabla(){
        for(int i=tblInventario.getRowCount()-1;i>=0;i--){
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel pnlbuscar;
    private javax.swing.JPanel pnlnventario;
    private javax.swing.JRadioButton rbtidprod;
    private javax.swing.JRadioButton rbtnombreprod;
    public javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtbuscarpor;
    public static javax.swing.JLabel txttitulo;
    // End of variables declaration//GEN-END:variables
}
